SELECT PRT.CDBASETASK, PRT.CDTASK, PRT.NMTASK, PRT.FGSINGLETASK 
FROM PRTASK PRT, GNASSOCSUITE GAM, GNMEETING ME WHERE PRT.CDASSOC = GAM.CDASSOCTO 
AND GAM.CDASSOCFROM = ME.CDASSOC AND ME.FGPHASE <> 6

SELECT * FROM PRTASK WHERE CDBASETASK = 21922

SELECT prt.cdbasetask, PRT.NMIDTASK, PRT.NMTASK, me.cdmeeting, ME.IDMEETING,ME.NMMEETING
 FROM PRTASK PRT, GNASSOCSUITE GAM, GNMEETING ME WHERE PRT.CDASSOC = GAM.CDASSOCTO 
AND GAM.CDASSOCFROM = ME.CDASSOC AND ME.FGPHASE <> 6 and CDBASETASK = 21922

SELECT prt.cdbasetask, prt.cdassoc AS CDASSOC_PROJ, PRT.NMIDTASK, PRT.NMTASK, me.cdmeeting, ME.IDMEETING, ME.NMMEETING, ME.CDASSOC
 FROM PRTASK PRT, GNASSOCSUITE GAM, GNMEETING ME 
 WHERE PRT.CDASSOC = GAM.CDASSOCTO 
AND GAM.CDASSOCFROM = ME.CDASSOC AND ME.FGPHASE <> 6 and CDBASETASK = 21922